app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/',['as'=>'root','uses'=>'PagesController@welcome']);
    Route::get('/login',['middleware'=>'guest','as'=>'login','uses'=>'AuthController@login']);
    Route::post('/handlelogin',['as'=>'handlelogin','uses'=>'AuthController@handle_login']);
    Route::get('/logout',['middleware'=>'auth','as'=>'logout','uses'=>'AuthController@logout']);
    Route::resource('users','UsersController',['only'=>['create','store']]);
    Route::resource('articles','ArticlesController');
});

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>InnFact | Laravel CMS</title>
	<link rel="stylesheet" href="{{ URL::asset('css/app.css') }}">
	<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"> -->


</head>
<body>
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			{{ link_to_route('root','InnFact',null,array('class' => 'navbar-brand')) }}
		</div>
		<ul class="navbar-nav nav navbar-right">
			@if(\Auth::check())
				<li><a href="#">Welcome {{camel_case(Auth::user()->name)}} </a></li>
				<li>{{ link_to_route('articles.create', 'Add Article') }}</li>
				<li>{{ link_to_route('articles.index', 'All Articles') }}</li>
				<li>{{ link_to_route('logout', 'Log Out') }}</li>
			@else
				<li>{{ link_to_route('users.create','Sign Up')}}</li>
				<li>{{ link_to_route('login','Sign In')}}</li>
			@endif
		</ul>
	</div>
</nav>
<div class="container">
	@yield('content')
</div>
</body>
</html>