app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
    Route::get('/',['as'=>'root','uses'=>'PagesController@welcome']);
    Route::get('/login',['middleware'=>'guest','as'=>'login','uses'=>'AuthController@login']);
    Route::post('/handlelogin',['as'=>'handlelogin','uses'=>'AuthController@handle_login']);
    Route::get('/logout',['middleware'=>'auth','as'=>'logout','uses'=>'AuthController@logout']);
    Route::resource('users','UsersController',['only'=>['create','store']]);
    Route::resource('articles','ArticlesController');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{

  protected $fillable = ['title','content','slug','user_id'];

  protected $table = 'articles';

  public static $create_validation_rules = [
    'title'=>'required',
    'content'=>'required',
    'slug'=>'required|unique:articles'
  ];

  public static $update_validation_rules = [
    'title'=>'required',
    'content'=>'required',
    'slug'=>'required'
  ];


  public function user()
  {
    $this->belongsTo('App\User');
  }
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Article;

class ArticlesController extends Controller
{

    public function __construct()
    {
      $this->middleware('auth',['except'=>['index','show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::all();
        return view('articles.index',compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,Article::$create_validation_rules);
        $data = $request->only('title','content','slug');
        $data['user_id'] = \Auth::user()->id;
        $article = Article::create($data);
        if($article)
        {
          return redirect()->route('articles.index');
        }
        else {
          return back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id)->firstOrFail();
        // dd($article->created_at);
        return view('articles.show',compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $article = Article::find($id)->firstOrFail();
      return view('articles.edit',compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request,Article::$update_validation_rules);
        $data = $request->only('title','content','slug');
        $article = Article::find($id)->firstOrFail();
        if($article)
        {
          $article->update($data);
          return redirect()->route('articles.show',$article->id);
        }

        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Article::destroy($id);
        return redirect()->route('articles.index');
    }
}

resources/views/articles/create.blade.php
@extends('layouts.master')

@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Create Article</h3>
      <hr/>
      {!! Form::open(array('route'=>'articles.store')) !!}
        <div class="form-group">
          <!-- {!! Form::label('title','Article Title') !!} -->
          {!! Form::text('title',null,array('class'=>'form-control','placeholder'=>'Article Title')) !!}
        </div>
        <div class="form-group">
          <!-- {!! Form::label('content','Write Article') !!} -->
          {!! Form::textarea('content',null,array('class'=>'form-control','placeholder'=>'Write Here..','rows'=>'5')) !!}
        </div>
        <div class="form-group">
          <!-- {!! Form::label('slug') !!} -->
          {!! Form::text('slug',null,array('class'=>'form-control','placeholder'=>'Article Slug')) !!}
        </div>
        <div class="form-group">
          {!! Form::token() !!}
          {!! Form::submit('Save',array('class'=>'form-control btn btn-success')) !!}
        </div>
      {!! Form::close() !!}
@endsection

resources/views/articles/edit.blade.php
@extends('layouts.master')

@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h3>Edit Article</h3>
      <hr/>
      {!! Form::model($article,array('route'=>array('articles.update',$article->id),'method'=>'put')) !!}
        <div class="form-group">
          <!-- {!! Form::label('title','Article Title') !!} -->
          {!! Form::text('title',null,array('class'=>'form-control','placeholder'=>'Article Title')) !!}
        </div>
        <div class="form-group">
          <!-- {!! Form::label('content','Write Article') !!} -->
          {!! Form::textarea('content',null,array('class'=>'form-control','placeholder'=>'Write Here..','rows'=>'5')) !!}
        </div>
        <div class="form-group">
          <!-- {!! Form::label('slug') !!} -->
          {!! Form::text('slug',null,array('class'=>'form-control','placeholder'=>'Article Slug')) !!}
        </div>
        <div class="form-group">
          {!! Form::token() !!}
          {!! Form::submit('Update',array('class'=>'form-control btn btn-info')) !!}
        </div>
      {!! Form::close() !!}
@endsection

resources/views/articles/index.blade.php
@extends('layouts.master')

@section('content')
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      @foreach($articles as $article)
        <div class="article">
          <h4>{{ link_to_route('articles.show',$article->title,array($article->id)) }}</h4>
          <div class="timestamp">Published at: {{ $article->created_at->format('d-m-y') }}</div>
          @if(\Auth::user())
            @if($article->user_id == \Auth::user()->id)
              <div class="action-btns">
                {{ link_to_route('articles.edit',"Edit",array($article->id),array('class'=>'edit-btn btn btn-primary btn-sm'))}}
                {{ link_to_route('articles.destroy',"Destroy",array($article->id),array('class'=>'edit-btn btn btn-danger btn-sm'))}}
              </div>
            @endif
          @endif
          <div class="body">
            {{ $article->content }}
          </div>
        </div>
      @endforeach
    </div>
  </div>
@endsection

resources/views/articles/show.blade.php
@extends('layouts.master')

@section('content')
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="article">
        <h4>{{ $article->title }}</h4>
        <div class="timestamp">Published at: {{ $article->created_at->format('d-m-y') }}</div>
        <div class="body">
          {{ $article->content }}
        </div>
      </div>
    </div>
  </div>
@endsection